import { useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { ArrowLeft, BookOpen, Clock, GitBranch } from 'lucide-react';
import { PageWrapper } from '@/components/layout/PageWrapper';
import { useDomainBySlugQuery } from '@/api/domains';
import { useEnrollmentsQuery } from '@/api/enrollments';
import { EnrollDialog } from './components/EnrollDialog';
import { getDomainMeta } from './lib/domainIcons';
import { PageSpinner } from '@/components/common/Spinner';

export default function DomainDetailPage() {
  const { slug = '' } = useParams<{ slug: string }>();
  const navigate = useNavigate();
  const [enrollOpen, setEnrollOpen] = useState(false);

  const { data: domain, isLoading } = useDomainBySlugQuery(slug);
  const { data: enrollments } = useEnrollmentsQuery();

  const enrollment = enrollments?.find((e) => e.domainId === domain?.id);
  const isEnrolled = Boolean(enrollment);
  const meta = getDomainMeta(slug);

  if (isLoading) return <PageSpinner />;

  if (!domain) {
    return (
      <PageWrapper>
        <p style={{ color: '#6e645a', fontFamily: "'Crimson Pro', serif" }}>Domain not found.</p>
        <Link to="/catalog" style={{ color: 'oklch(0.62 0.18 28)' }}>← Back to catalog</Link>
      </PageWrapper>
    );
  }

  return (
    <PageWrapper>
      {/* Back */}
      <Link
        to="/catalog"
        className="inline-flex items-center gap-1.5 text-sm mb-8 hover:underline"
        style={{ color: '#9a9088', fontFamily: "'Crimson Pro', serif" }}
      >
        <ArrowLeft size={14} />
        Back to Catalog
      </Link>

      {/* Header */}
      <div className="flex items-start gap-5 mb-8">
        <div
          className="w-16 h-16 rounded-2xl flex-shrink-0 flex items-center justify-center text-3xl"
          style={{ background: meta.color, color: meta.accent }}
        >
          {domain.iconUrl ? (
            <img src={domain.iconUrl} alt="" className="w-9 h-9 object-contain" />
          ) : (
            <span style={{ fontFamily: 'monospace' }}>{meta.icon}</span>
          )}
        </div>
        <div>
          <h1
            className="text-[38px] leading-tight"
            style={{ fontFamily: "'Cormorant Garamond', serif", color: '#3d342a' }}
          >
            {domain.name}
          </h1>
          {domain.description && (
            <p className="mt-1 text-[16px] max-w-xl" style={{ color: '#6e645a', fontFamily: "'Crimson Pro', serif" }}>
              {domain.description}
            </p>
          )}
        </div>
      </div>

      {/* Stats bar */}
      <div
        className="flex flex-wrap gap-6 px-6 py-4 rounded-2xl border mb-8"
        style={{ background: '#f3efe7', borderColor: '#d6cfbf' }}
      >
        <Stat icon={<BookOpen size={15} />} label="Learning nodes" value="40+" />
        <Stat icon={<Clock size={15} />} label="Estimated time" value="~80 hrs" />
        <Stat icon={<GitBranch size={15} />} label="Branch paths" value="3" />
      </div>

      {/* AI personalisation note */}
      <div
        className="rounded-2xl border px-6 py-5 mb-8 max-w-xl"
        style={{ background: '#faf7f1', borderColor: '#d6cfbf' }}
      >
        <p className="text-sm font-medium mb-1" style={{ color: '#3d342a', fontFamily: "'Cormorant Garamond', serif", fontSize: 17 }}>
          Personalised Roadmap
        </p>
        <p className="text-[14px]" style={{ color: '#6e645a', fontFamily: "'Crimson Pro', serif" }}>
          Your roadmap is generated by AI based on your free time, familiarity, and learning goals —
          then fleshed out by a Teacher Model that explains each concept in context.
        </p>
      </div>

      {/* CTA */}
      {isEnrolled ? (
        <button
          onClick={() => navigate(`/enrollments/${enrollment!.id}/roadmap`)}
          className="inline-flex items-center gap-2 rounded-xl px-6 py-3 text-base font-semibold transition-all active:scale-[0.98]"
          style={{ background: 'oklch(0.62 0.18 28)', color: '#faf7f1', fontFamily: "'Crimson Pro', serif" }}
        >
          Continue Learning →
        </button>
      ) : (
        <button
          onClick={() => setEnrollOpen(true)}
          className="inline-flex items-center gap-2 rounded-xl px-6 py-3 text-base font-semibold transition-all active:scale-[0.98]"
          style={{ background: 'oklch(0.62 0.18 28)', color: '#faf7f1', fontFamily: "'Crimson Pro', serif" }}
        >
          Enroll Now
        </button>
      )}

      {enrollOpen && (
        <EnrollDialog domain={domain} open={enrollOpen} onClose={() => setEnrollOpen(false)} />
      )}
    </PageWrapper>
  );
}

function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) {
  return (
    <div className="flex items-center gap-2">
      <span style={{ color: '#9a9088' }}>{icon}</span>
      <span className="text-sm" style={{ color: '#6e645a', fontFamily: "'Crimson Pro', serif" }}>
        {label}:
      </span>
      <span className="text-sm font-medium" style={{ color: '#3d342a', fontFamily: "'Crimson Pro', serif" }}>
        {value}
      </span>
    </div>
  );
}
